name: Android Build and Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Set up Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          sudo mkdir -p $HOME/Android/Sdk
          sudo apt-get install -y --no-install-recommends zipalign

      - name: Install dependencies
        run: flutter pub get

      - name: Copy Python tools
        run: |
          chmod +x mobile-app/copy-tools-to-python.sh
          cd mobile-app && ./copy-tools-to-python.sh

      - name: Build APK
        run: |
          chmod +x mobile-app/build-android-embedded.sh
          cd mobile-app && ./build-android-embedded.sh release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: mobile-app/build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Publish Release APK
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-unsigned

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app-release-unsigned.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release - ${{ github.ref_name }}"
          body: |
            This release was built automatically. See attached APK file.
          draft: false
          prerelease: false
